CREATE TABLE proveedores (
  id_proveedor integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL UNIQUE,
  estado boolean NOT NULL DEFAULT true,
  fecha_creacion timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE maquinas (
  id_maquina integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo text NOT NULL UNIQUE,
  nombre text NOT NULL,
  descripcion text NOT NULL DEFAULT '',
  ubicacion text NOT NULL,
  estado text NOT NULL DEFAULT 'ACTIVA' CHECK (estado IN ('ACTIVA', 'INACTIVA', 'MANTENCION')),
  fecha_creacion timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE productos (
  id_producto integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL UNIQUE,
  precio_venta numeric(12, 2) NOT NULL CHECK (precio_venta >= 0),
  costo_compra numeric(12, 2) NOT NULL DEFAULT 0 CHECK (costo_compra >= 0),
  estado boolean NOT NULL DEFAULT true,
  fecha_creacion timestamptz NOT NULL DEFAULT now(),
  id_proveedor integer REFERENCES proveedores(id_proveedor) ON DELETE SET NULL
);

CREATE TABLE maquina_productos (
  id_maquina_producto integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_maquina integer NOT NULL REFERENCES maquinas(id_maquina) ON DELETE CASCADE,
  id_producto integer NOT NULL REFERENCES productos(id_producto) ON DELETE RESTRICT,
  capacidad_maxima integer NOT NULL CHECK (capacidad_maxima >= 0),
  stock_actual integer NOT NULL CHECK (stock_actual BETWEEN 0 AND capacidad_maxima),
  precio_venta_actual numeric(12, 2) NOT NULL CHECK (precio_venta_actual >= 0),
  estado boolean NOT NULL DEFAULT true,
  UNIQUE (id_maquina, id_producto)
);

CREATE TABLE usuarios (
  id_usuario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL,
  apellido text NOT NULL,
  email text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  rol text NOT NULL CHECK (rol IN ('ADMIN', 'REPONEDOR')),
  estado boolean NOT NULL DEFAULT true,
  fecha_creacion timestamptz NOT NULL DEFAULT now()
);
