CREATE TABLE reposiciones (
  id_reposicion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_maquina integer NOT NULL REFERENCES maquinas(id_maquina),
  dinero_retirado numeric(12, 2) NOT NULL CHECK (dinero_retirado >= 0),
  observacion text,
  venta_esperada numeric(12, 2) NOT NULL CHECK (venta_esperada >= 0),
  diferencia_dinero numeric(12, 2) NOT NULL,
  fecha_creacion timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE reposicion_detalles (
  id_reposicion_detalle integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_reposicion integer NOT NULL REFERENCES reposiciones(id_reposicion) ON DELETE CASCADE,
  id_maquina_producto integer NOT NULL REFERENCES maquina_productos(id_maquina_producto),
  stock_sistema integer NOT NULL CHECK (stock_sistema >= 0),
  stock_encontrado integer NOT NULL CHECK (stock_encontrado >= 0),
  cantidad_vendida integer NOT NULL CHECK (cantidad_vendida >= 0),
  cantidad_repuesta integer NOT NULL CHECK (cantidad_repuesta >= 0),
  cantidad_retirada integer NOT NULL CHECK (cantidad_retirada >= 0),
  stock_final integer NOT NULL CHECK (stock_final >= 0),
  precio_venta_actual numeric(12, 2) NOT NULL CHECK (precio_venta_actual >= 0),
  venta_esperada numeric(12, 2) NOT NULL CHECK (venta_esperada >= 0)
);

CREATE INDEX reposiciones_id_maquina_fecha_idx ON reposiciones (id_maquina, fecha_creacion DESC);
CREATE INDEX reposicion_detalles_id_reposicion_idx ON reposicion_detalles (id_reposicion);
