BEGIN;

CREATE TABLE bodega_productos (
  id_producto integer PRIMARY KEY REFERENCES productos(id_producto),
  stock_actual integer NOT NULL DEFAULT 0 CHECK (stock_actual >= 0)
);

CREATE TABLE bodega_movimientos (
  id_movimiento integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_producto integer NOT NULL REFERENCES productos(id_producto),
  tipo text NOT NULL CHECK (tipo IN ('ENTRADA', 'SALIDA')),
  cantidad integer NOT NULL CHECK (cantidad > 0),
  stock_final integer NOT NULL CHECK (stock_final >= 0),
  observacion text,
  fecha_creacion timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX bodega_movimientos_producto_idx ON bodega_movimientos (id_producto);

COMMIT;
