BEGIN;

CREATE TABLE camionetas (
  id_camioneta integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patente text NOT NULL UNIQUE CHECK (patente <> '' AND patente = upper(btrim(patente))),
  nombre text NOT NULL CHECK (btrim(nombre) <> ''),
  id_repartidor integer NOT NULL UNIQUE REFERENCES usuarios(id_usuario),
  estado boolean NOT NULL DEFAULT true,
  fecha_creacion timestamptz NOT NULL DEFAULT now()
);

COMMIT;
