BEGIN;

CREATE TABLE camioneta_productos (
  id_camioneta integer NOT NULL REFERENCES camionetas(id_camioneta),
  id_producto integer NOT NULL REFERENCES productos(id_producto),
  stock_actual integer NOT NULL DEFAULT 0 CHECK (stock_actual >= 0),
  PRIMARY KEY (id_camioneta, id_producto)
);

CREATE TABLE camioneta_movimientos (
  id_movimiento integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_camioneta integer NOT NULL REFERENCES camionetas(id_camioneta),
  id_producto integer NOT NULL REFERENCES productos(id_producto),
  id_bodeguero integer NOT NULL REFERENCES usuarios(id_usuario),
  id_repartidor integer NOT NULL REFERENCES usuarios(id_usuario),
  id_movimiento_bodega integer NOT NULL UNIQUE REFERENCES bodega_movimientos(id_movimiento),
  cantidad integer NOT NULL CHECK (cantidad > 0),
  stock_final integer NOT NULL CHECK (stock_final >= 0),
  observacion text,
  fecha_creacion timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX camioneta_movimientos_camioneta_idx ON camioneta_movimientos (id_camioneta, id_movimiento DESC);

COMMIT;
