BEGIN;

CREATE TABLE conteos (
  id_conteo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_camioneta integer REFERENCES camionetas(id_camioneta) ON DELETE RESTRICT,
  id_producto integer NOT NULL REFERENCES productos(id_producto) ON DELETE RESTRICT,
  id_responsable integer NOT NULL REFERENCES usuarios(id_usuario) ON DELETE RESTRICT,
  stock_esperado integer NOT NULL CHECK (stock_esperado >= 0),
  stock_fisico integer NOT NULL CHECK (stock_fisico >= 0),
  diferencia integer GENERATED ALWAYS AS (stock_fisico - stock_esperado) STORED,
  observacion text,
  fecha_creacion timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX conteos_ubicacion_idx ON conteos (id_camioneta, id_conteo DESC);

COMMIT;
