BEGIN;

-- Repair databases where the header exists but migration 001's details are missing.
CREATE TABLE IF NOT EXISTS reposicion_detalles (
  id_reposicion_detalle integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_reposicion integer NOT NULL REFERENCES reposiciones(id_reposicion) ON DELETE CASCADE,
  id_maquina_producto integer NOT NULL REFERENCES maquina_productos(id_maquina_producto),
  stock_sistema integer NOT NULL CHECK (stock_sistema >= 0),
  stock_encontrado integer NOT NULL CHECK (stock_encontrado >= 0),
  cantidad_vendida integer NOT NULL CHECK (cantidad_vendida >= 0),
  cantidad_repuesta integer NOT NULL CHECK (cantidad_repuesta >= 0),
  cantidad_retirada integer NOT NULL CHECK (cantidad_retirada >= 0),
  stock_final integer NOT NULL CHECK (stock_final >= 0),
  precio_venta_actual numeric(12, 2) NOT NULL CHECK (precio_venta_actual >= 0),
  venta_esperada numeric(12, 2) NOT NULL CHECK (venta_esperada >= 0)
);

CREATE INDEX IF NOT EXISTS reposicion_detalles_id_reposicion_idx
  ON reposicion_detalles (id_reposicion);

COMMIT;
